//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVacationReservation.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BookingSoap")]
    public interface BookingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchFlight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchFlight(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchFlight", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchFlightAsync(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingSoapChannel : OnlineVacationReservation.ServiceReference1.BookingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingSoapClient : System.ServiceModel.ClientBase<OnlineVacationReservation.ServiceReference1.BookingSoap>, OnlineVacationReservation.ServiceReference1.BookingSoap {
        
        public BookingSoapClient() {
        }
        
        public BookingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet searchFlight(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City) {
            return base.Channel.searchFlight(Departing_Country, Departing_City, Destination_Country, Destination_City);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchFlightAsync(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City) {
            return base.Channel.searchFlightAsync(Departing_Country, Departing_City, Destination_Country, Destination_City);
        }
    }
}
